# Generated by Django 3.1 on 2021-03-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_department_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='used',
            field=models.BooleanField(default=True),
        ),
    ]
